XBackend/XBackend/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from samplexray.views import load_ensemble_model, load_pytorch_model

load_ensemble_model()
load_pytorch_model()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chexray/', include('samplexray.urls')),

    #REST_FRAMEWORK_URLS
    path('api/chexray/', include('samplexray.api.urls', 'samplexray-api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

XBackend/samplexray/api/urls.py
from django.urls import path
#from rest_framework.authtoken.views import obtain_auth_token

from samplexray.api.views import (
    registration_view,
    custom_obtain_auth_token,
    api_detail_user_view,
    api_detail_xray_view,
    api_upload_xray_view,
    api_anonupload_xray_view,
    )

app_name = 'samplexray'

urlpatterns = [
    path('xray/', api_detail_xray_view, name='api-xraydetail'),
    path('user/', api_detail_user_view, name='api-userdetail'),
    path('login/', custom_obtain_auth_token, name='api-login'),
    path('signup/', registration_view, name='api-signup'),
    path('upload/', api_upload_xray_view, name='api-upload'),
    path('anonupload/', api_anonupload_xray_view, name='api-anonupload'),
]

XBackend/samplexray/urls.py
from django.urls import path

from . import views


app_name = 'samplexray'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    #path('profile/<int:user_id>/results/<int:xray_id>/', views.predict, name='predict'),
    #path('results/<int:xray_id>/', views.anonpredict, name='anonpredict'),
    path('profile/<int:user_id>/upload/', views.xrayupload, name='upload'),
    path('upload/', views.xrayanonupload, name='anonupload'),
]

XBackend/samplexray/models.py
from .dictionary import Dictionary

from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver

from rest_framework.authtoken.models import Token

# Create your models here.
"""
def upload_location(instance, filename, **kwargs):
	file_path = 'chex/anon/'
"""

class XRaySample(models.Model):
	title = models.CharField(max_length = 50, null = False, blank = False)
	image = models.ImageField(upload_to='images/', null = False, blank = False)
	date_posted = models.DateTimeField(auto_now_add = True, verbose_name = "date posted")
	userperson = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
	heatmap_image = models.ImageField(upload_to='heatmaps/', null = False, blank = True)

	
	cardiomegaly = models.FloatField(default = 0.0)
	edema = models.FloatField(default = 0.0)
	consolidation = models.FloatField(default = 0.0)
	atelectasis = models.FloatField(default = 0.0)
	pleural_effusion = models.FloatField(default = 0.0)

	"""
	cool = models.FloatField(default = 0.0)
	fist = models.FloatField(default = 0.0)
	ok = models.FloatField(default = 0.0)
	stop = models.FloatField(default = 0.0)
	yo = models.FloatField(default = 0.0)
	"""
	#"Cardiomegaly", "Edema", "Consolidation", "Atelectasis", "Pleural Effusion"
	def __str__(self):
		return self.title

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
	if created:
		Token.objects.create(user=instance)

XBackend/samplexray/forms.py
from django import forms
from .models import *

class XrayForm(forms.ModelForm):

	class Meta :
		model = XRaySample
		fields = ['title', 'image']

XBackend/samplexray/api/views.py
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.authtoken.models import Token
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.permissions import IsAuthenticated

from django.contrib.auth.models import User
from django.core.files import File

from samplexray.models import XRaySample
from samplexray.api.serializers import XRaySampleSerializer, RegistrationSerializer
from samplexray.views import return_prediction, generate_heatmap

import os

CURRENT_PATH = os.getcwd()

@api_view(['POST',])
def registration_view(request):
    if request.method == 'POST':
        serializer = RegistrationSerializer(data=request.data)
        data = {}
        if serializer.is_valid():
            user = serializer.save()
            data['response'] = "Successfully Signed Up"
            data['username'] = user.username
            token = Token.objects.get(user=user).key
            data['token'] = token
        else:
            data = serializer.errors
        return Response(data)


#Login method
from rest_framework import parsers, renderers
from rest_framework.authtoken.models import Token
from rest_framework.authtoken.serializers import AuthTokenSerializer
from rest_framework.compat import coreapi, coreschema
from rest_framework.response import Response
from rest_framework.schemas import ManualSchema
from rest_framework.schemas import coreapi as coreapi_schema
from rest_framework.views import APIView


class CustomAuthToken(APIView):
    throttle_classes = ()
    permission_classes = ()
    parser_classes = (parsers.FormParser, parsers.MultiPartParser, parsers.JSONParser,)
    renderer_classes = (renderers.JSONRenderer,)
    serializer_class = AuthTokenSerializer

    if coreapi_schema.is_enabled():
        schema = ManualSchema(
            fields=[
                coreapi.Field(
                    name="username",
                    required=True,
                    location='form',
                    schema=coreschema.String(
                        title="Username",
                        description="Valid username for authentication",
                    ),
                ),
                coreapi.Field(
                    name="password",
                    required=True,
                    location='form',
                    schema=coreschema.String(
                        title="Password",
                        description="Valid password for authentication",
                    ),
                ),
            ],
            encoding="application/json",
        )

    def get_serializer_context(self):
        return {
            'request': self.request,
            'format': self.format_kwarg,
            'view': self
        }

    def get_serializer(self, *args, **kwargs):
        kwargs['context'] = self.get_serializer_context()
        return self.serializer_class(*args, **kwargs)

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data['user']
        token, created = Token.objects.get_or_create(user=user)

        data= {}
        data['userid'] = user.id
        data['username'] = user.username
        data['token'] = token.key
        return Response(data)


custom_obtain_auth_token = CustomAuthToken.as_view()


@api_view(['GET',])
@permission_classes((IsAuthenticated,))
def api_detail_user_view(request):
    if request.method == "GET":
        logged_in_user = request.user

        user_pastxray_list = logged_in_user.xraysample_set.all().order_by('-date_posted')
        data = {}
        data['userid'] = logged_in_user.id
        data['username'] = logged_in_user.username
        data['pastxrays'] = [xray_sample.id for xray_sample in user_pastxray_list]

        return Response(data)


@api_view(['POST', ])
@permission_classes((IsAuthenticated,))
def api_detail_xray_view(request):
    
    if request.method == "POST":
        try :
            xray_sample = XRaySample.objects.get(pk=request.data.get('xray_id'))
        except XRaySample.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

        user = request.user
        
        if xray_sample.userperson != user :
            return Response({'response' : "You don't have permission to view this."})

        serializer = XRaySampleSerializer(xray_sample)
        return Response(serializer.data)



@api_view(['POST',])
@permission_classes((IsAuthenticated,))
def api_upload_xray_view(request):
    user = request.user
    xray_post = XRaySample(userperson=user)
    if request.method == 'POST' :
        serializer = XRaySampleSerializer(xray_post, data=request.data)
        if serializer.is_valid():
            serializer.save()
            input_file_path = os.path.join(CURRENT_PATH + xray_post.image.url)
            prediction_list = return_prediction(input_file_path)
            
            output_file_path = os.path.join(CURRENT_PATH + "/media/heatmaps/" + "heatmap_" + xray_post.image.name.split('/')[-1])
            generate_heatmap(input_file_path, output_file_path)

            f = File(open(output_file_path,'rb'))
            xray_post.heatmap_image.save("heatmap_" + xray_post.image.name.split('/')[-1], f)

            xray_post.atelectasis, xray_post.cardiomegaly, xray_post.consolidation, xray_post.edema, xray_post.pleural_effusion = prediction_list
            xray_post.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)



@api_view(['POST',])
def api_anonupload_xray_view(request):
    """
    Keeping first user as the anonymous user
    """
    anonuser = User.objects.get(pk=1)
    xray_post = XRaySample(userperson=anonuser)
    if request.method == 'POST' :
        serializer = XRaySampleSerializer(xray_post, data=request.data)
        if serializer.is_valid():
            serializer.save()
            input_file_path = os.path.join(CURRENT_PATH + xray_post.image.url)
            prediction_list = return_prediction(input_file_path)

            output_file_path = os.path.join(CURRENT_PATH + "/media/heatmaps/" + "heatmap_" + xray_post.image.name.split('/')[-1])
            generate_heatmap(input_file_path, output_file_path)

            f = File(open(output_file_path,'rb'))
            xray_post.heatmap_image.save("heatmap_" + xray_post.image.name.split('/')[-1], f)
            
            xray_post.atelectasis, xray_post.cardiomegaly, xray_post.consolidation, xray_post.edema, xray_post.pleural_effusion = prediction_list
            xray_post.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

XBackend/samplexray/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.models import AnonymousUser, User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.conf import settings

# Create your views here.

from .forms import XrayForm
from .models import XRaySample
from .dictionary import Dictionary

from keras.models import model_from_json
from keras.preprocessing import image
import keras.backend.tensorflow_backend as tb
import tensorflow as tf
from keras.applications.densenet import preprocess_input
import h5py
import numpy as np
import os

from .heatmap_utils import load_torch_model
from .heatmap_utils.generate_heatmap import HeatmapGenerator

from .ensemble_utils.ensemble import Ensemble

CURRENT_PATH = os.getcwd()
ANOMALY_INDICES = {0 : 'Atelectasis', 1 : 'Cardiomegaly', 2 : 'Consolidation', 3 : 'Edema', 4 : 'Pleural Effusion'}
ENSEMBLE_OBJECT_GLOBAL = None
PYTORCH_HEATMAP_MODEL = None

#SET TENSORFLOW ENVIRONMENT TO OPTIMAL
physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)
tb._SYMBOLIC_SCOPE.value = True


"""
-------------------------
AUTHENTICATION AREA ---->
-------------------------
"""


def index(request):
    return render(request, 'samplexray/index.html')

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log in the user too !
            return redirect("samplexray:login")
    else:
        form = UserCreationForm()
    return render(request, 'samplexray/signup.html', {'form' : form})


def login(request):

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return HttpResponseRedirect(reverse('samplexray:profile', args=(user.id,)))
    else:
        form = AuthenticationForm()
    return render(request, 'samplexray/login.html', {'form' : form})

@login_required(login_url='/samplexray/login/')
def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('samplexray:index'))


"""
---------------------------------------
MODEL LOADING AND PREDICTION AREA ---->
---------------------------------------
"""


def load_pytorch_model():
	global PYTORCH_HEATMAP_MODEL
	PYTORCH_HEATMAP_MODEL = load_torch_model.build_model()
	print("PyTorch TarBall Loaded :p")


def generate_heatmap(input_file_path, output_file_path):
	global PYTORCH_HEATMAP_MODEL	

	if PYTORCH_HEATMAP_MODEL is None :
		print("WARNING : PYTORCH MODEL REQUIRED AGAIN MEMORY LEAKAGE !")
		PYTORCH_HEATMAP_MODEL = load_torch_model.build_model()

	h = HeatmapGenerator(PYTORCH_HEATMAP_MODEL)
	h.generate(input_file_path, output_file_path)


def load_ensemble_model():
	global ENSEMBLE_OBJECT_GLOBAL
	ENSEMBLE_OBJECT_GLOBAL = Ensemble()
	ENSEMBLE_OBJECT_GLOBAL.build_models()

def return_prediction(file_path):
	global ENSEMBLE_OBJECT_GLOBAL

	if ENSEMBLE_OBJECT_GLOBAL is None :
		ENSEMBLE_OBJECT_GLOBAL.build_models()

	return ENSEMBLE_OBJECT_GLOBAL.get_predictions(file_path)


"""
DJANGO TEMPLATES AREA --->
"""


@login_required(login_url='/samplexray/login/')
def profile(request, user_id):
    if(user_id == request.user.id):
        user = get_object_or_404(User, pk=user_id)
        pastxrays = user.xraysample_set.all().order_by('-date_posted')
        return render(request, 'samplexray/profile.html', {"user" : user, 'pastxrays' : pastxrays})
    else:
        return HttpResponse("Bad Request")


@login_required(login_url='/samplexray/login/')
def xrayupload(request, user_id):

	if(user_id == request.user.id):
		user = get_object_or_404(User, pk=user_id)
		if request.method == 'POST':
			form = XrayForm(request.POST, request.FILES)
			if form.is_valid():
				xrayTitle = form.cleaned_data['title']
				xrayImage = form.cleaned_data['image']
				xrayUser = user
				xrayDate_posted = timezone.now()

				newxray = XRaySample(title = xrayTitle, date_posted = xrayDate_posted, userperson = xrayUser, image = xrayImage,)
				newxray.save()

				disease_preds = return_prediction(os.path.join(CURRENT_PATH + newxray.image.url))
				#newxray.cool, newxray.fist, newxray.ok, newxray.stop, newxray.yo = disease_preds[0]
				newxray.atelectasis, newxray.cardiomegaly, newxray.consolidation, newxray.edema, newxray.pleural_effusion = disease_preds[0]
				newxray.save()
				
				return render(request, 'samplexray/result.html', {'xrayobj' : newxray, 'prediction' : disease_preds, 'anomaly_indices' : ANOMALY_INDICES})
				#return HttpResponseRedirect(reverse('samplexray:predict', args=(user.id, newxray.id,)))
		else:
			form = XrayForm()

		return render(request, 'samplexray/upload.html', {'form' : form, 'user' : user})

def xrayanonupload(request):
	if request.method == 'POST':
		form = XrayForm(request.POST, request.FILES)
		if form.is_valid():
			xrayTitle = form.cleaned_data['title']
			xrayImage = form.cleaned_data['image']
			
			path = default_storage.save(os.path.join('images/' + xrayTitle + '.jpg'), ContentFile(xrayImage.read()))
			display_path = os.path.join(settings.MEDIA_URL , path)
			tmp_file = os.path.join(settings.MEDIA_ROOT , path)

			prediction = return_prediction(tmp_file)
			
			return render(request, 'samplexray/anonresult.html', {'xraytitle' : xrayTitle, 'xrayimgurl' : display_path, 'prediction' : prediction, 'anomaly_indices' : ANOMALY_INDICES})
	else:
		form = XrayForm()
	return render(request, 'samplexray/anonupload.html', {'form' : form})

XBackend/samplexray/templates/samplexray/anonresult.html
{% extends 'samplexray/base.html' %}
{% block content %}
  <style>
    .btn-primary{
        padding: 3px 15px;
        border: 1px solid green;
    }
    img {
        padding: 5px;
        width: 300px;
    }
    .displayresult {
        display : block;
    }
  </style>
<head>
    <meta charset="UTF-8">
    <title>CheXRay Result</title>
    <a class='btn btn-primary' href="{% url 'samplexray:login' %}">Login</a>
    <a class='btn btn-primary' href="{% url 'samplexray:signup' %}">SignUp</a>
    <a class='btn btn-primary' href="{% url 'samplexray:anonupload' %}">Upload</a>
    <h1>Thanks for using PerXeptron CheXRay !</h1>
    <h4>Here, are your results :</h4><br>

    <div class  = "displayresult">
        <h2>{{ xraytitle }}</h2>
        <img class="img-responsive" src = "{{ xrayimgurl }}"/>
        <h3>Predictions :</h3>
        <h3>{{ anomaly_indices }}</h3>
        <h3>{{ prediction }}</h3>
    </div>
<head>
{% endblock %}

XBackend/samplexray/templates/samplexray/anonupload.html
{% extends 'samplexray/base.html' %}
{% block content %}
<style>
  p {
    font-family: "Open Sans";
    font-size: 18px;
    text-align: center;
    display: block;
  }
</style>
<head>
    <meta charset="UTF-8">
    <title>Submit XRay Image</title>
</head>
<body>
  <a class='btn btn-primary' href="{% url 'samplexray:login' %}">Login</a>
  <a class='btn btn-primary' href="{% url 'samplexray:signup' %}">SignUp</a>
  <h1>Submit XRay Image</h1>
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <center><input type="submit" value="Get Prediction"></center>
    </form>
</body>
{% endblock %}

XBackend/samplexray/templates/samplexray/base.html
{% load static %}
<body>
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</body>
{% block content %}
{% endblock %}

XBackend/samplexray/templates/samplexray/index.html
{% extends 'samplexray/base.html' %}
{% block content %}
  <style>
    .btn-primary{
      padding: 3px 15px;
      border: 1px solid green;
    }
  </style>
<head>
    <meta charset="UTF-8">
    <title>PerXeptron CheXRay</title>
    <a class='btn btn-primary' href="{% url 'samplexray:login' %}">Login</a>
    <a class='btn btn-primary' href="{% url 'samplexray:signup' %}">SignUp</a>
    <a class='btn btn-primary' href="{% url 'samplexray:anonupload' %}">Upload</a>
    <h1>Welcome to The PerXeptron CheXRay !</h1>
    <h4>A lightweight, fast deep learning enabled Chest X-Ray Anomaly detection application developed by PerXeptron</h4><br>
<head>
{% endblock %}

XBackend/samplexray/templates/samplexray/login.html
{% extends 'samplexray/base.html' %}
{% block content %}
<style>
  input[type=text] {
      font-size: 16px;
  }
</style>
<head>  
  <meta charset="UTF-8">
  <a class='btn btn-primary' href="{% url 'samplexray:signup' %}">SignUp</a>
  <a class='btn btn-primary' href="{% url 'samplexray:anonupload' %}">Upload</a>
  <h1>Login</h1>
  <form class="site-form" action="{% url 'samplexray:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
  </form>
</head>
{% endblock content %}

XBackend/samplexray/templates/samplexray/profile.html
{% extends 'samplexray/base.html' %}
{% block content %}
<head>
  <a class="btn btn-primary" href="{% url 'samplexray:logout' %}">Logout</a>
  <a class="btn btn-primary" href="{% url 'samplexray:upload' user.id %}">Upload</a>
  <h1>Your profile</h1>
  <h3>Welcome back ! {{ user.username }}</h3><br>
  <h2>Your Recent XRays</h2>
    <table>
      <col span = "4"/>
      <ul>
        {% for xray in pastxrays %}
          <tr>
            <td><li><img src="{{ xray.image.url }}" class = "img-responsive" width = 200px></td> 
            <td>{{ xray.title }}</td>
            <td>{{xray.cool}}, {{xray.fist}}, {{xray.ok}}, {{xray.stop}}, {{xray.yo}}</td>
            <td>Report Date : {{ xray.date_posted.date }}</td></li>
          </tr>
        {% endfor %}
      </ul>
    </table>
</head>
{% endblock %}

XBackend/samplexray/templates/samplexray/result.html
{% extends 'samplexray/base.html' %}
{% block content %}
  <style>
    .btn-primary{
        padding: 3px 15px;
        border: 1px solid green;
    }
    img {
        padding: 5px;
        width: 300px;
    }
    .displayresult {
        display : block;
    }
  </style>
<head>
    <meta charset="UTF-8">
    <title>CheXRay Result</title>
    <a class='btn btn-primary' href="{% url 'samplexray:logout' %}">Logout</a>
    <a class='btn btn-primary' href="{% url 'samplexray:profile' user.id %}">Go Back</a>
    <a class='btn btn-primary' href="{% url 'samplexray:upload' user.id %}">Upload Again</a>
    <h1>Thanks for using PerXeptron CheXRay !</h1>
    <h4>Here, are your results :</h4><br>

    <div class  = "displayresult">
        <h2>{{ xrayobj.title }}</h2>
        <img class="img-responsive" src = "{{ xrayobj.image.url }}"/>
        <h3>Predictions :</h3>
        <h3>{{ anomaly_indices }}</h3>
        <h3>{{ prediction }}</h3>
    </div>
<head>
{% endblock %}

XBackend/samplexray/templates/samplexray/signup.html
{% extends 'samplexray/base.html' %}
{% block content %}
<meta charset="UTF-8">
<a class='btn btn-primary' href="{% url 'samplexray:login' %}">Login</a>
<a class='btn btn-primary' href="{% url 'samplexray:anonupload' %}">Upload</a>
  <h1>Signup</h1>
  <form class="site-form" action="{% url 'samplexray:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
  </form>
{% endblock %}

XBackend/samplexray/templates/samplexray/upload.html
{% extends 'samplexray/base.html' %}
{% block content %}
<style>
  p {
    font-family: "Open Sans";
    font-size: 18px;
    text-align: center;
    display: block;
  }
</style>
<head>
    <meta charset="UTF-8">
    <title>Submit XRay Image</title>
</head>
<body>
  <a class='btn btn-primary' href="{% url 'samplexray:logout' %}">Logout</a>
  <a class='btn btn-primary' href="{% url 'samplexray:profile' user.id %}">Go Back</a>
  <h1>Submit XRay Image</h1>
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <center><input type="submit" value="Get Prediction"></center>
    </form>
</body>
{% endblock %}